pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/HariMuthuGanesh/DevOps.git'
            }
        }
        stage('Install dependencies') {
            steps {
                dir('Student_Management') {
                    bat 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir('Student_Management') {
                    bat 'npm run build'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('Student_Management') {
                    bat 'if not exist "C:\\ProgramData\\Jenkins\\.jenkins\\userContent\\studentmanagement" mkdir "C:\\ProgramData\\Jenkins\\.jenkins\\userContent\\studentmanagement"'
                    bat 'xcopy /E /I /Y "dist\\*" "C:\\ProgramData\\Jenkins\\.jenkins\\userContent\\studentmanagement\\"'
                }
            }
        }
    }

    post {
        success {
            echo 'Student Management Application built and deployed successfully!'
        }
        failure {
            echo 'Student Management Pipeline Build Failed!'
        }
    }
}
